# Generated by Django 2.2.2 on 2019-06-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='curr_balance',
            field=models.IntegerField(),
        ),
    ]
